from agents import Agent, Handoff
from dotenv import load_dotenv
from openai import OpenAI
from planner_agent import planner_agent
from search_agent import search_agent
from writer_agent import writer_agent
from email_agent import email_agent

load_dotenv(override=True)

client = OpenAI()

planner_tool = planner_agent.as_tool(
    tool_name="planner_agent",
    tool_description="Plan which searches to perform for a research query."
)

search_tool = search_agent.as_tool(
    tool_name="search_agent",
    tool_description="Perform searches for the items in the plan."
)

writer_tool = writer_agent.as_tool(
    tool_name="writer_agent",
    tool_description="Write the research report from search results."
)

email_tool = email_agent.as_tool(
    tool_name="email_agent",
    tool_description="Send the final report to the user."
)

research_agent = Agent(
    name="Research Orchestrator",
    instructions="""
You are the Research Manager. Your job is to coordinate planning, searching, report writing, 
and emailing using the appropriate sub-agents.
You only output final results unless you are calling a tool.

Follow this workflow:

1. Receive the user's research query.

2. Call the planner_agent tool to generate a WebSearchPlan.
   - The plan must include a set of search items and the reason for each.

3. After receiving the plan, call the search_agent tool once for each search item.
   - Aggregate and summarize all search results.

4. After all searches are completed, call the writer_agent tool to produce a polished,
   markdown-formatted research report that includes:
   - The original query
   - A synthesis of all search results
   - Clear structure and professionalism

5. After the report is created, call the email_agent tool to send the report to the user.

6. Your **final output** (after all tool calls are complete) must be only the full
   markdown report generated by writer_agent.

Rules:
- Do not perform planning, searching, writing, or emailing yourself.
- Delegate every step to its proper tool.
- Only produce messages when required for a tool call or final output.
""",
    tools=[planner_tool, search_tool, writer_tool, email_tool]
)